import logging
from typing import Any, Dict
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.conf import settings
from rest_framework.request import Request
from .serializers import TokenObtainSerializer, ChatMessageSerializer
from .permissions import HasValidAPIKey
from .clients import OllamaClient
import jwt
from datetime import timedelta
from django.utils import timezone

logger = logging.getLogger(__name__)


class TokenObtainView(APIView):
    """
    Accepts api_key, verifies it, and returns a signed JWT token.
    """

    def post(self, request: Request) -> Response:
        serializer = TokenObtainSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        api_key: str = serializer.validated_data["api_key"]
        expected_api_key: str = settings.EXPECTED_API_KEY

        logger.debug(f"Token obtain attempt with API key: {api_key}")

        if api_key != expected_api_key:
            logger.warning(f"Invalid API key attempt: {api_key}")
            return Response(
                {"detail": "Invalid API key"},
                status=status.HTTP_401_UNAUTHORIZED,
            )

        now = timezone.now()
        payload: Dict[str, Any] = {
            "sub": "service-api",
            "iat": int(now.timestamp()),
            "exp": int((now + timedelta(hours=1)).timestamp()),
        }

        jwt_secret: str = settings.JWT_SECRET_KEY
        token = jwt.encode(payload, jwt_secret, algorithm="HS256")

        logger.debug("JWT token successfully generated")

        return Response({"jwt": token}, status=status.HTTP_200_OK)


class ChatSessionView(APIView):
    """
    Protected chat endpoint that requires a valid Bearer JWT token.
    """

    permission_classes = [HasValidAPIKey]

    def post(self, request: Request) -> Response:
        serializer = ChatMessageSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        logger.debug("Chat session request validated")

        client = OllamaClient()
        response = client.generate(serializer.validated_data["message"])

        logger.debug("Chat response generated by OllamaClient")

        return Response({"response": response}, status=status.HTTP_200_OK)
